apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-node-smith
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/StealthBadger747/KubeNodeSmith.git
    targetRevision: main
    path: manifests/app
  destination:
    server: https://kubernetes.default.svc
    namespace: kubenodesmith
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
