---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenodesmith-deployment
  namespace: kubenodesmith
  labels:
    app: kubenodesmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenodesmith
  template:
    metadata:
      labels:
        app: kubenodesmith
    spec:
      serviceAccountName: kubenodesmith
      containers:
      - name: kubenodesmith
        image: stealthbadger747/kubenodesmith:main
        imagePullPolicy: Always
        volumeMounts:
        - name: scaler-config
          mountPath: /config
          readOnly: true
        env:
        - name: PROXMOX_SECRET
          valueFrom:
            secretKeyRef:
              name: proxmox-api-secret
              key: PROXMOX_SECRET
        - name: SCALER_CONFIG_PATH
          value: /config/scaler-config.yaml
        ports:
          - name: http-health
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-health
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-health
          initialDelaySeconds: 2
          periodSeconds: 10
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists 
          effect: NoSchedule
      volumes:
      - name: scaler-config
        configMap:
          name: scaler-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenodesmith
  namespace: kubenodesmith
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenodesmith
rules:
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
# Needed to list pods by Node
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Needed to cordon Nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch", "list", "update", "delete"]
# Needed to determine Pod owners
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list"]
# Needed to determine Pod owners
- apiGroups: ["extensions"]
  resources: ["daemonsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenodesmith
subjects:
- kind: ServiceAccount
  name: kubenodesmith
  apiGroup: ""
  namespace: kubenodesmith
roleRef:
  kind: ClusterRole
  name: kubenodesmith
  apiGroup: ""
