apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenodesmith-deployment
  namespace: kubenodesmith
  labels:
    app: kubenodesmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenodesmith
  template:
    metadata:
      labels:
        app: kubenodesmith
    spec:
      containers:
      - name: kubenodesmith
        image: stealthbadger747/kubenodesmith:main
        env:
        - name: PROXMOX_SECRET
          valueFrom:
            secretKeyRef:
              name: proxmox-api-secret
              key: PROXMOX_SECRET
