apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenodesmith-deployment
  namespace: kubenodesmith
  labels:
    app: kubenodesmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenodesmith
  template:
    metadata:
      labels:
        app: kubenodesmith
    spec:
      containers:
      - name: kubenodesmith
        image: stealthbadger747/kubenodesmith:main
        imagePullPolicy: Always
        env:
        - name: PROXMOX_SECRET
          valueFrom:
            secretKeyRef:
              name: proxmox-api-secret
              key: PROXMOX_SECRET
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists 
          effect: NoSchedule
