apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-echo
  template:
    metadata:
      labels:
        app: hello-echo
    spec:
      containers:
        - name: echoserver
          image: cilium/echoserver:1.10.3
          ports:
            - containerPort: 8080
          resources:
            requests: { memory: "9Gi", cpu: "3500m" }
            limits:   { memory: "9Gi", cpu: "3500m" }
---
apiVersion: v1
kind: Service
metadata:
  name: hello-echo
spec:
  selector:
    app: hello-echo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
