apiVersion: kubenodesmith.kubenodesmith.parawell.cloud/v1alpha1
kind: NodeSmithPool
metadata:
  labels:
    app.kubernetes.io/name: kubenodesmith
    app.kubernetes.io/managed-by: kustomize
  name: nodesmithpool-sample
spec:
  # TODO(user): Add fields here
